import { Agent } from "@cursor/sdk";
import {
  LIBRARIES_ROOT,
  buildPrompt,
  extractJson,
  heuristicPlan,
  loadLibraries,
  validatePlacements,
} from "./libraries.js";

/**
 * Ask Cursor SDK (composer-2.5) where to place library assets on the timeline.
 * Falls back to a deterministic heuristic if CURSOR_API_KEY is missing or the call fails.
 */
export async function enhanceWithCursor({ captions, duration, forceHeuristic = false }) {
  const libraries = loadLibraries();
  const payload = {
    captions: (captions || []).map((c) => ({
      text: String(c.text ?? ""),
      startTime: Number(c.startTime) || 0,
      endTime: Number(c.endTime) || 0,
    })),
    duration: Number(duration) || 10,
    libraries,
  };

  if (forceHeuristic || !process.env.CURSOR_API_KEY) {
    return {
      ...heuristicPlan(payload),
      model: null,
      note: forceHeuristic
        ? "Forced heuristic mode"
        : "CURSOR_API_KEY missing — used offline heuristic with the same JSON schema",
    };
  }

  const prompt = buildPrompt(payload);

  try {
    const result = await Agent.prompt(prompt, {
      apiKey: process.env.CURSOR_API_KEY,
      model: { id: "composer-2.5" },
      local: {
        cwd: LIBRARIES_ROOT,
        // Keep this run read-only / low-tool: we only need a JSON answer.
      },
    });

    if (result.status !== "finished" || !result.result) {
      throw new Error(result.error?.message || `Agent status: ${result.status}`);
    }

    const parsed = extractJson(result.result);
    const plan = validatePlacements({ ...parsed, source: "cursor-sdk" }, libraries);
    return {
      ...plan,
      model: result.model?.id || "composer-2.5",
      usage: result.usage,
      durationMs: result.durationMs,
      note: "Placements generated by Cursor SDK (@cursor/sdk)",
    };
  } catch (error) {
    const fallback = heuristicPlan(payload);
    return {
      ...fallback,
      model: null,
      note: `Cursor SDK failed (${error.message}); used heuristic fallback`,
    };
  }
}
